name: simple-classifier-ci

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python and install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the classification script
        run: |
          python model.py
